### PR TITLE
added a command to generate random members

### PR DESCRIPTION
**Pull request by tanelikaivola**

### CODE REVIEW

**Comment by jautero** [comment]
I get following exception: 
```
(asylum-venv)asylum@a8a536ccc71d:/opt/asylum$ ./manage.py generate_members
Traceback (most recent call last):
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/query.py", line 405, in get_or_create
    return self.get(**lookup), False
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
members.models.DoesNotExist: Member matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/asylum/members/management/commands/generate_members.py", line 41, in handle
    UserFactory()
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/base.py", line 81, in __call__
    return cls.create(**kwargs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/base.py", line 567, in create
    return cls._generate(True, attrs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/base.py", line 492, in _generate
    obj = cls._prepare(create, **attrs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/base.py", line 467, in _prepare
    return cls._create(model_class, *args, **kwargs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/django.py", line 172, in _create
    return cls._get_or_create(model_class, *args, **kwargs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/django.py", line 163, in _get_or_create
    obj, _created = manager.get_or_create(*args, **key_fields)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/query.py", line 407, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/asylum/members/models.py", line 85, in save
    return super().save(*args, **kwargs)
  File "/opt/asylum/asylum/mixins.py", line 15, in save
    return super().save(*args, **kwargs)
  File "/opt/asylum/asylum/mixins.py", line 26, in save
    self.full_clean()
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/base.py", line 1171, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'email': ['Sy\xf6t\xe4 kelvollinen s\xe4hk\xf6postiosoite.']}
```

**Comment by ojousima** [comment]
I get similar error,

```
asylum@a2b2fc392fc8:/opt/asylum$ ./manage.py generate_members
Traceback (most recent call last):
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/query.py", line 405, in get_or_create
    return self.get(**lookup), False
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
members.models.DoesNotExist: Member matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/asylum/members/management/commands/generate_members.py", line 41, in handle
    UserFactory()
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/base.py", line 81, in __call__
    return cls.create(**kwargs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/base.py", line 567, in create
    return cls._generate(True, attrs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/base.py", line 492, in _generate
    obj = cls._prepare(create, **attrs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/base.py", line 467, in _prepare
    return cls._create(model_class, *args, **kwargs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/django.py", line 172, in _create
    return cls._get_or_create(model_class, *args, **kwargs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/factory/django.py", line 163, in _get_or_create
    obj, _created = manager.get_or_create(*args, **key_fields)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/query.py", line 407, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "/opt/asylum-venv/lib/python3.4/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/asylum/members/handlers.py", line 43, in wrapper
    instance.on_saving(*args, **kwargs)
TypeError: on_saving() got an unexpected keyword argument 'using'
```

**Comment by jautero** [comment]
The backtrace does not come always which indicates that it happens only on certain names. So, most likely culprit is scandinavian letters in a name.

**Comment by rambo** [comment]
Superceded by #110

**Pull request closed without merging**
